name: build-and-test
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/workflows/**'
      - '**/README*'
      - '**/readme*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # https://remarkablemark.org/blog/2021/03/14/setup-postgresql-in-github-actions/
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: nest-back-dev-2-test
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: debug
        run: |
          echo event: ${{ github.event_name }}
          echo ref: ${{ github.ref }}

      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm ci

      - name: install postgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: setup test env
        run: |
          echo "${{ secrets.ENV_TEST }}" >> .env.test
          mkdir -p ./env
          mv .env.test ./env

      - name: build and test
        run: |
          npm run build
          npm run test
          npm run test:e2e
